driver:
  name: vagrant

provisioner:
  name: chef_zero
  clients_path: ./spec/data/clients
  nodes_path: ./spec/data/nodes

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-8
    run_list: apt::default
  - name: fedora-27
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[materialize::_test]
      - recipe[materialize::_test_read]
    attributes:
